# General training
experiment_name: ddq_msa_easyWordv2_P43_O2O
resume: False
device: cuda:0
val_interval: 1
debug_mode: False  # Doesn't save checkpoints
seed: 10

epochs: 2000
lr: 2e-4
lr_backbone: 2e-5
lr_linear_proj_mult: 0.1
weight_decay: 1e-4
clip_max_norm: -1
log_grad: True
log_grad_every_epoch: 10

# Scheduler
lr_drop: 500

# Data
dataset: easy_wordv2_224_224_160_CT
overfit: False # Use same set consisting of one image for train and val
bbox_padding: 1

# Dataloader
batch_size: 1
shuffle: True
num_workers: 8

focal_loss: False

# Hungarian matching
set_cost_class: 2
set_cost_bbox: 5
set_cost_giou: 2
hybrid_dense_matching: False
dense_matching: False #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
dense_matching_lambda: 0.5
class_matching: False
class_matching_query_split: [10,20,20,30,20] # 10 for liver, 30 for pancreas, 20 for each other organ

# Losses
loss_coefs:
  cls: 2      # Detection
  bbox: 5
  giou: 2
  segce: 2    # Segmentation proxy
  segdice: 2




# Model specific params
backbone:
  name: msavit

  # Standard params
  msa: True
  in_channels: 1  #  Input channels 
  start_channels: 32  # Channels after first encoder block
  bias: False
  norm_type: instance
  data_size: [224, 224, 160] 

  
  # Standard params
  fpn_channels: 384 # Final output channels
  out_fmaps: [P4, P3]  # P0, P1, P2, P3, P4, P5

  kernel_size: 3
  patch_size: 2
  mlp_ratio: 2
  num_heads: 32
  depths: 2
  drop_path_rate: 0.0
  attn_drop_rate: 0.0
  drop_rate: 0.0
  qkv_bias: True
  cuda: 0
  bias: False


  # Segmentation proxy loss
  num_organs: 10
  use_msa_seg_loss: True #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  fg_bg: False
  use_seg_proxy_loss: False  # never use it with msa





neck:
  name: def_detr
  use_encoder: True 
  input_level: P3
  num_feature_levels: 2

  pos_encoding: sine
  hidden_dim: 384
  dropout: 0.1
  nheads: 6
  dim_feedforward: 1024
  enc_layers: 3
  dec_layers: 3
  enc_n_points: 4
  dec_n_points: 4
  num_queries: 100
  aux_loss: True
  use_cuda: False

  # contrastive learning params
  contrastive:
    enabled: False # False in this study
    mom: 0.999
    dim: 256
    eqco: 1000
    tau: 0.7
    loss_coeff: 0.2

  dn:
    type: cdn
    enabled: False #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    multiscale: False
    dn_number: 20  # number of dn groups 
    dn_box_noise_ratio: 0.4
    multiscale_box_noise_ratio_max: 0  #it is necessary if multi_scale is true
    dn_label_noise_ratio: 0.5
    multiscale_label_noise_ratio_max: 0 #it is necessary if multi_scale is true
    
    
# Augmentation
augmentation:
  use_augmentation: True
  patch_size: [224, 224, 160]  

  p_gaussian_noise: 0
  p_gaussian_smooth: 0
  p_intensity_scale: 0.5
  p_intensity_shift: 0.5
  p_adjust_contrast: 0
  p_rotate: 0.5
  p_zoom: 0.5
  p_shear: 0
  p_translate: 0.5
  p_flip: 0

  gaussian_noise_mean: 0.0
  gaussian_noise_std: 0.1
  gaussian_smooth_sigma: [0.5, 1.0]

  intensity_scale_factors: 0.1
  intensity_shift_offsets: 0.1

  adjust_contrast_gamma: [0.7, 1.5]

  rotation: [-5, 5]
  min_zoom: 0.9
  max_zoom: 1.1
  translate_precentage: 10
  shear_range: [0.1, 0.1, 0.1]
  flip_axis: [0, 1, 2]
