# Config file for AttnFPN-def-DETR

# General training
experiment_name: resnet_def_detr_abdomenCT1k
device: cuda:0
val_interval: 1
debug_mode: False  # Doesn't save checkpoints
seed: 10

epochs: 4000
lr: 2e-4
lr_backbone: 2e-5
lr_linear_proj_mult: 0.1
weight_decay: 1e-4
clip_max_norm: -1   # Not used

# Scheduler
lr_drop: 2500

# Data
dataset: abdomenCT-1k_128_128_64_reg_CT
overfit: False # Use same set consisting of one image for train and val
bbox_padding: 1

# Dataloader
batch_size: 2
shuffle: True
num_workers: 10

# Hungarian matching
set_cost_class: 2
set_cost_bbox: 5
set_cost_giou: 2

# Losses
loss_coefs:
  cls: 2      # Detection
  bbox: 5
  giou: 2
  segce: 2    # Segmentation proxy
  segdice: 2

# Model specific params
backbone:
  name: resnet
  out_channels: 384
  # Segmentation proxy loss
  use_seg_proxy_loss: False
  fg_bg: True

neck:
  name: def_detr
  use_encoder: True
  input_level: res3
  num_feature_levels: 3

  pos_encoding: sine
  hidden_dim: 384
  dropout: 0.1
  nheads: 6
  dim_feedforward: 1024
  enc_layers: 3
  dec_layers: 3
  enc_n_points: 4
  dec_n_points: 4
  num_queries: 100
  aux_loss: True
  use_cuda: False
  use_msa_seg_loss: False
  contrastive:
    enabled: False
    mom: 0.999
    dim: 256
    eqco: 1000
    tau: 0.7
    loss_coeff: 0.2
  dn:
    enabled: True
    type: dn
    dn_number: 3  # number of dn groups
    dn_box_noise_ratio: 0.2 # 0.4
    dn_label_noise_ratio: 0.25 # 0.5

# Augmentation
augmentation:
  use_augmentation: True
  patch_size: [128, 128, 64] 

  p_gaussian_noise: 0
  p_gaussian_smooth: 0
  p_intensity_scale: 0.5
  p_intensity_shift: 0.5
  p_adjust_contrast: 0
  p_rotate: 0.5
  p_zoom: 0.5
  p_shear: 0
  p_translate: 0.5
  p_flip: 0

  gaussian_noise_mean: 0.0
  gaussian_noise_std: 0.1
  gaussian_smooth_sigma: [0.5, 1.0]

  intensity_scale_factors: 0.1
  intensity_shift_offsets: 0.1

  adjust_contrast_gamma: [0.7, 1.5]

  rotation: [-5, 5]
  min_zoom: 0.9
  max_zoom: 1.1
  translate_precentage: 10
  shear_range: [0.1, 0.1, 0.1]
  flip_axis: [0, 1, 2]
