# Config file for AttnFPN-def-DETR

# General training
experiment_name: ALL_TRA_CFG_EasyWord_v2_swin_unetr_hugarian
device: cuda:0
val_interval: 1
debug_mode: False  # Doesn't save checkpoints
seed: 10

epochs: 2000
lr: 2e-4
lr_backbone: 2e-5
lr_linear_proj_mult: 0.1
weight_decay: 1e-4
clip_max_norm: 1

# Scheduler
lr_drop: 1250

# Data
dataset: easy_wordv2_224_224_160_CT
overfit: False # Use same set consisting of one image for train and val
bbox_padding: 1

# Dataloader
batch_size: 2
shuffle: True
num_workers: 10

# Hungarian matching
set_cost_class: 2
set_cost_bbox: 5
set_cost_giou: 2
dense_matching: False
dense_matching_lambda: 0.2

# Losses
focal_loss: False
loss_coefs:
  cls: 2      # Detection
  bbox: 5
  giou: 2
  segce: 2    # Segmentation proxy
  segdice: 2

# Model specific params
backbone:
  name: swin_unetr
  data_size: [224, 224, 160]
  pretrained: False # if True, in_channels, out_channels and feature_size are set automatically
  in_channels: 1
  out_channels: 1 # won't use
  start_channels: 24  # Channels after first encoder block
  feature_size: 48 # controls out channels
  drop_rate: 0
  attn_drop_rate: 0
  use_checkpoint: True
  fpn_channels: 384

  # Segmentation proxy loss
  num_organs: 10
  use_seg_proxy_loss: False
  fg_bg: False
  use_msa_seg_loss: False

neck:
  name: def_detr
  use_encoder: True
  input_level: P2
  num_feature_levels: 3

  pos_encoding: sine
  hidden_dim: 384
  dropout: 0.1
  nheads: 6
  dim_feedforward: 1024
  enc_layers: 3
  dec_layers: 3
  enc_n_points: 4
  dec_n_points: 4
  num_queries: 100
  aux_loss: True
  use_cuda: False

  # contrastive learning params
  contrastive:
    enabled: False
    mom: 0.999
    dim: 256
    eqco: 1000
    tau: 0.7
    loss_coeff: 0.2

  dn:
    enabled: False
    dn_number: 3  # number of dn groups 
    dn_box_noise_ratio: 0.2 # 0.4 
    dn_label_noise_ratio: 0.25 # 0.5

# Augmentation
augmentation:
  use_augmentation: True
  patch_size: [224, 224, 160]

  p_gaussian_noise: 0
  p_gaussian_smooth: 0
  p_intensity_scale: 0.5
  p_intensity_shift: 0.5
  p_adjust_contrast: 0
  p_rotate: 0.5
  p_zoom: 0.5
  p_shear: 0
  p_translate: 0.5
  p_flip: 0

  gaussian_noise_mean: 0.0
  gaussian_noise_std: 0.1
  gaussian_smooth_sigma: [0.5, 1.0]

  intensity_scale_factors: 0.1
  intensity_shift_offsets: 0.1

  adjust_contrast_gamma: [0.7, 1.5]

  rotation: [-5, 5]
  min_zoom: 0.9
  max_zoom: 1.1
  translate_precentage: 10
  shear_range: [0.1, 0.1, 0.1]
  flip_axis: [0, 1, 2]
